"""
Stated Targets Analysis - Template

This script generates plots comparing stated targets vs bottom-up projections.
Based on the workflow in main.py (lines 192-340).
"""

import typer
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
from config import load_config
import copy

from src.datasets.GSPTDataset import GSPTDataset
from src.datasets.RefinitivDataset import RefinitivDataset
from src.datasets.utils import convert_plant2parent
from src.projections_.targets import preprocess_targets, get_stated_traj, merge_all_traj, get_sub_traj_melt, get_bu_vs_stated_fig


def main(config_path: Path = typer.Argument(Path("./config.toml"), help="Path to the TOML configuration file")):
    """Generate stated targets vs bottom-up projections plots."""
    
    # ========================================================================
    # STEP 1: LOAD CONFIGURATION AND SETUP PATHS
    # ========================================================================
    # Load config file
    # Get project directory, scenario_level, model_name, EAF_decarb from params
    # Define raw_data_dir path
    # Define output paths: plots_dir, plots_data_dir
    # Create output directories
    
    
    # ========================================================================
    # STEP 2: LOAD MAPPINGS
    # ========================================================================
    # Load gspt2gspt_path (JSON file for GSPT name cleanup)
    # Load parent_group_map_path (JSON file for company groupings)
    
    
    # ========================================================================
    # STEP 3: LOAD GSPT DATASET
    # ========================================================================
    # Initialize GSPTDataset with:
    #   - asset_level_data path
    #   - missing_years path
    #   - gspt2gspt_path
    #   - parent_group_map_path
    #   - version_year=2023
    
    
    # ========================================================================
    # STEP 4: LOAD REFINITIV DATA
    # ========================================================================
    # Initialize RefinitivDataset with refinitiv_path
    # Get preprocessed data
    # This is needed for preprocess_targets()
    
    
    # ========================================================================
    # STEP 5: LOAD HISTORICAL BU EMISSIONS
    # ========================================================================
    # Two options:
    # OPTION A: Compute from scratch using get_historical_bu_emissions()
    #   - Need: EF, prod_dir, global_capa_path, global_prod_wsa_path, etc.
    #   - Returns: agg_bu_histo (aggregate) and group_bu_histo (by company)
    #   - See main.py lines 167-177
    
    # OPTION B: Load from Excel file (if already generated by final_plots.py)
    #   - Read: plots_data_dir / "historical_bu_emissions.xlsx"
    #   - Contains columns: year, Emissions (Gt), Attributed production
    #   - Convert Emissions (Gt) to BU emissions in tonnes: * 1e9
    #   - Then compute group_bu_histo by allocating to companies based on capacity shares
    #   - See final_stated_targets.py old version lines 77-104
    
    
    # ========================================================================
    # STEP 6: LOAD BOTTOM-UP PROJECTIONS
    # ========================================================================
    # Load pickle file: raw_data_dir / "results_data" / f"bu_proj_{scenario_level}_{model_name}_EAF_decarb.pkl"
    # This contains nested dict structure:
    #   bu_proj[scenario][method]["company"] = DataFrame with columns:
    #     - year
    #     - Group
    #     - BU emissions (method_name)
    # Scenarios: ["NZE", "APS", "STEPS"]
    # Methods: ["constant_UR", "company_UR"]
    # See main.py lines 188-190
    
    
    # ========================================================================
    # STEP 7: LOAD AND PREPROCESS TARGETS
    # ========================================================================
    # Load targets file: raw_data_dir / "targets/2030_unique_targets.xlsx"
    # Preprocess using preprocess_targets():
    #   - Pass: targets_path, refinitiv, gspt2gspt_path
    #   - Returns: DataFrame with GSPT_Name, CAGR, Baseline Year Emissions, etc.
    # Merge with group_bu_histo to get 2022 BU emissions for each company:
    #   - Filter group_bu_histo where year == 2022
    #   - Merge on "Group" column
    # See main.py lines 192-201
    
    
    # ========================================================================
    # STEP 8: GET STATED TRAJECTORIES
    # ========================================================================
    # Use get_stated_traj() to calculate company trajectories:
    #   - Pass: targets, emissions_col='BU emissions'
    #   - Returns: DataFrame with columns: year, Group, Stated BU emissions
    #   - For each company, calculates trajectory from 2022 to 2030 using CAGR
    # See main.py lines 203-204
    
    
    # ========================================================================
    # STEP 9: MERGE STATED TRAJECTORIES WITH BU PROJECTIONS
    # ========================================================================
    # Define scenarios and methods:
    #   scenarios = ["NZE", "APS", "STEPS"]
    #   methods = ["constant_UR", "company_UR"]
    
    # Use merge_all_traj() to combine:
    #   - stated_traj (from step 8)
    #   - bu_proj (from step 6)
    #   - scenarios list
    #   - methods list
    # Returns: all_traj DataFrame with columns:
    #   - year, Group, Stated BU emissions
    #   - NZE_BU emissions (constant_UR), NZE_BU emissions (company_UR)
    #   - APS_BU emissions (constant_UR), APS_BU emissions (company_UR)
    #   - STEPS_BU emissions (constant_UR), STEPS_BU emissions (company_UR)
    # See main.py lines 205-209
    
    
    # ========================================================================
    # STEP 10: REMOVE PROBLEMATIC COMPANIES
    # ========================================================================
    # Filter out: all_traj = all_traj.loc[all_traj["Group"] != "Ternium SA"]
    # See main.py line 210
    
    
    # ========================================================================
    # STEP 11: PREPROCESS TRAJECTORIES FOR PLOTTING
    # ========================================================================
    # Fill missing values using forward fill:
    #   all_traj = all_traj.fillna(method="ffill", axis=1)
    
    # Define data types:
    #   dtypes = {'year': int, 'Group': object}
    #   float_columns = all_traj.columns.difference(['year', 'Group'])
    #   dtypes.update({col: float for col in float_columns})
    #   all_traj = all_traj.astype(dtypes)
    
    # Create scenario-specific stated emissions columns (for easier manipulation):
    #   for scenario in scenarios:
    #       all_traj[f"{scenario}_Stated BU emissions"] = all_traj["Stated BU emissions"].copy()
    # See main.py lines 211-223
    
    
    # ========================================================================
    # STEP 12: DEFINE COMPANY SUBSAMPLES
    # ========================================================================
    # Three groups of interest:
    # 1. All companies with stated targets:
    #    companies_with_stated = list(stated_traj['Group'].unique())
    
    # 2. Top 5 emitters with targets:
    #    top5_companies = ["ArcelorMittal SA", "JSW Steel Ltd", "Nippon Steel Corp", 
    #                      "POSCO Holding Co.", "Shougang Group Co Ltd"]
    
    # 3. Companies with both taxonomy alignment and stated targets:
    #    taxonomy_companies = ["Acerinox SA", "Aperam SA", "ArcelorMittal SA", 
    #                          "Danieli & C Officine Meccaniche SpA", "Outokumpu Oyj", 
    #                          "Salzgitter AG", "Tenaris SA", "thyssenkrupp AG", "voestalpine AG"]
    
    # Store in dict:
    #   subsamples = {"stated": companies_with_stated, 
    #                 "top5": top5_companies, 
    #                 "taxo": taxonomy_companies}
    # See main.py lines 226-231
    
    
    # ========================================================================
    # STEP 13: COMPUTE CAPACITY SHARES (OPTIONAL - FOR REPORTING)
    # ========================================================================
    # Get 2022 capacity data:
    #   plant_capa22 = gspt.get_operating_plants(start_year=2022)
    #   group_capa22 = convert_plant2parent(plant_capa22, gspt2gspt_path, parent_group_map)
    #   group_capa22["Attributed capacity (ttpa)"] = 
    #       group_capa22['Nominal crude steel capacity (ttpa)'] * group_capa22["Share"]
    #   group_capa22 = group_capa22.groupby(["Group", "year"])["Attributed capacity (ttpa)"].sum().reset_index()
    
    # Calculate share for each subsample:
    #   total_capa = 2459000  # Global total capacity
    #   for prefix, companies in subsamples.items():
    #       sum_capa = group_capa22.loc[group_capa22["Group"].isin(companies), "Attributed capacity (ttpa)"].sum()
    #       capa_share = sum_capa / total_capa
    #       print(f"{prefix}: {capa_share*100:.2f}% of global capacity")
    # See main.py lines 233-250
    
    
    # ========================================================================
    # STEP 14: CREATE STATED TARGETS VS BU PLOTS (LEVELS)
    # ========================================================================
    # Loop through each subsample:
    #   for prefix, companies in subsamples.items():
    
    # For each subsample:
    # 1. Get melted trajectory data:
    #    sub_traj_melt = get_sub_traj_melt(all_traj, companies)
    #    This aggregates by year and melts to long format for plotting
    
    # 2. Set plot title based on subsample:
    #    if prefix == "stated":
    #        title = "Stated emissions vs bottom-up emissions for all companies with stated targets in 2030"
    #    elif prefix == "top5":
    #        title = "Stated emissions vs bottom-up emissions for top 5 emitters with stated targets in 2030"
    #    elif prefix == "taxo":
    #        title = "Stated emissions vs bottom-up emissions for 9 companies with both taxonomy and stated targets in 2030"
    
    # 3. Generate figure using get_bu_vs_stated_fig():
    #    fig = get_bu_vs_stated_fig(sub_traj_melt, group_bu_histo, companies)
    #    This creates a 1x3 subplot (one for each scenario: NZE, APS, STEPS)
    #    Shows: historical BU, stated trajectory, BU projections
    
    # 4. Save figure:
    #    fig_path = plots_dir / f"{prefix}_stated_traj_scenarios.pdf"
    #    fig.savefig(fig_path, bbox_inches='tight', dpi=600)
    # See main.py lines 256-270
    
    
    # ========================================================================
    # STEP 15: CREATE PERCENTAGE DEVIATION PLOTS
    # ========================================================================
    # Still in the loop for each subsample:
    
    # 1. Separate BU projections from stated targets:
    #    bu_sub_traj = sub_traj_melt.loc[sub_traj_melt["Source"] != "Stated emissions"]
    #    stated_sub_traj = sub_traj_melt.loc[sub_traj_melt["Source"] == "Stated emissions"]
    
    # 2. Merge BU with stated on year and scenario:
    #    pct_dev_traj = pd.merge(bu_sub_traj, stated_sub_traj,
    #                            how="left", on=["year", "Scenario"],
    #                            suffixes=("_bu", "_stated"))
    
    # 3. Calculate percentage deviation:
    #    pct_dev_traj["pct_misalignment"] = 
    #        100 * (pct_dev_traj.Emissions_bu - pct_dev_traj.Emissions_stated) / pct_dev_traj.Emissions_stated
    
    # 4. Add subsample label:
    #    pct_dev_traj["Subsample"] = prefix
    
    # 5. Append to list for later plotting:
    #    subsamples_df.append(pct_dev_traj)
    # See main.py lines 273-282
    
    
    # ========================================================================
    # STEP 16: CREATE COMBINED PERCENTAGE DEVIATION FIGURE
    # ========================================================================
    # After the loop, combine all subsamples:
    #   subsamples_df = pd.concat(subsamples_df, axis=0, ignore_index=True)
    
    # Create 2x3 subplot figure (2 methods × 3 scenarios):
    #   fig, axs = plt.subplots(2, 3, figsize=(12, 6), sharey=True)
    
    # Loop through methods and scenarios:
    #   for i, method in enumerate(methods):
    #       for j, scenario in enumerate(scenarios):
    #           ax = axs[i, j]
    #           
    #           # Filter data for this method and scenario
    #           m1 = subsamples_df["Scenario"] == scenario
    #           m2 = subsamples_df["Source_bu"] == method  # or use .str.contains(method)
    #           
    #           # Plot lines for each subsample
    #           sns.lineplot(subsamples_df.loc[m1 & m2],
    #                       x="year", y="pct_misalignment",
    #                       hue="Subsample", linestyle="--", ax=ax)
    #           
    #           # Set title and labels
    #           ax.set_title(scenario)
    #           if "constant_UR" in method:
    #               mname = "country UR"
    #           elif "company_UR" in method:
    #               mname = "constant market share"
    #           ax.set_ylabel(f"% overshoot \n ({mname})")
    #           
    #           # Remove individual legends (will create figure-level legend)
    #           if (i == 0) & (j == 0):
    #               legend_handles_labels = ax.get_legend_handles_labels()
    #           ax.get_legend().remove()
    
    # Add figure-level title and legend:
    #   title = "Relative deviation of bottom-up projections from the stated emissions trajectory \n" \
    #           "for 3 subsets of companies with stated targets"
    #   fig.suptitle(title)
    #   
    #   handles, labels = legend_handles_labels
    #   fig.legend(handles=handles, labels=labels, 
    #             loc='outside lower center', ncol=3, frameon=False)
    
    # Save figure:
    #   fig.tight_layout()
    #   fig_path = plots_dir / "pct_misalignment.pdf"
    #   fig.savefig(fig_path, bbox_inches='tight', dpi=600)
    # See main.py lines 284-328
    
    
    # ========================================================================
    # STEP 17: CREATE TWO-SUBSAMPLE VERSION (OPTIONAL)
    # ========================================================================
    # Create copy of figure and remove taxonomy group:
    #   fig_two = copy.deepcopy(fig)
    #   for ax in fig_two.get_axes():
    #       for line in ax.get_lines():
    #           label = line.get_label()
    #           if label == "taxo":
    #               line.remove()
    
    # Save:
    #   fig_two_path = plots_dir / "pct_misalignment_2.pdf"
    #   fig_two.savefig(fig_two_path, bbox_inches='tight', dpi=600)
    # See main.py lines 330-340
    
    
    # ========================================================================
    # STEP 18: SAVE DATA TO EXCEL (OPTIONAL)
    # ========================================================================
    # Save all trajectories:
    #   all_traj.to_excel(plots_data_dir / "stated_targets_all_trajectories.xlsx", index=False)
    
    # Save percentage deviation data:
    #   subsamples_df.to_excel(plots_data_dir / "stated_targets_pct_deviation.xlsx", index=False)
    
    # Save capacity shares:
    #   capacity_shares_df = pd.DataFrame(list(capacity_shares.items()), 
    #                                     columns=['Subsample', 'Capacity Share'])
    #   capacity_shares_df.to_excel(plots_data_dir / "capacity_shares.xlsx", index=False)
    
    
    # ========================================================================
    # STEP 19: PRINT SUMMARY
    # ========================================================================
    # Print summary of outputs:
    #   - Number of plots created
    #   - Location of plots
    #   - Capacity shares for each subsample
    #   - Any warnings or notes
    
    pass


if __name__ == "__main__":
    typer.run(main)

