[project]
authors = ["Hamada Saleh <hamada.saleh@institutlouisbachelier.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "bottom_up_alignment"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
jupyter = ">=1.1.1,<2"
ipykernel = ">=6.29.5,<7"
ruff = ">=0.7.4,<0.8"
pandas = ">=2.2.3,<3"
python-calamine = ">=0.5.3,<0.6"
matplotlib = ">=3.10.5,<4"
typer = ">=0.19.2,<0.20"
toml = ">=0.10.2,<0.11"
joblib = ">=1.5.2,<2"
seaborn = ">=0.13.2,<0.14"
pydantic = ">=2.11.9,<3"
scikit-learn = ">=1.7.2,<2"
adjusttext = ">=1.3.0,<2"
openpyxl = ">=3.1.5,<4"
pyarrow = ">=21.0.0,<22"
